### ISSUE TITLE
mix styles when writing a TOML document?

### ISSUE THREAD

**Issue by hydrargyrum** [python-poetry/tomlkit#348]
It's not documented, yet it seems possible to do:

```
import tomlkit
data = {
    "mykey": tomlkit.string("foo\nbar", multiline=True),
}
print(tomlkit.dumps(data))
```

thus mixing 2 styles:
- a `tomlkit.string`
- a regular python dict (no `tomlkit.TOMLDocument`, no `tomlkit.<anything>`)

is it a feature? a bug? will this behaviour stay or is there no such guarantee?

**Comment by frostming** [comment]
You can do both, `tomlkit.api.*` is used when you need to control the formats. E.g. you can pass `literal=True` to `tomlkit.string()` to use single quotes.
