### ISSUE TITLE
`tomlkit` 0.12.5 : Encoder contract interferes with external `TypeError`s raised in encoders

### ISSUE THREAD

**Issue by sanmai-NL** [python-poetry/tomlkit#355]
## Problem

`register_encoder` expects encoder functions to raise a `TypeError` when encoding fails. `TypeError`s are an error class not specific to `tomlkit`, however, and this causes interference and unclear tracebacks.

For example:
```
> /Users/user/bla/__main__.py(50)encoder()
-> if any(
(Pdb) n
TypeError: any() takes exactly one argument (6 given)
(Pdb) c
...
  File "/Users/user/bla/.venv/lib/python3.12/site-packages/tomlkit/items.py", line 218, in item
    raise _ConvertError(f"Invalid type {type(value)}")
tomlkit.items._ConvertError: Invalid type <class 'Legitimateclass'>
```

## Solution

Change the API to use a `tomlkit`-specific and fine-grained, encoder-specific exception class.

**Comment by frostming** [comment]
Can you show me how the TypeError occurs? It seems like the encoder is not well implemented.

Library and frameworks should be loose about input and strict about output.

**Comment by sanmai-NL** [comment]
@frostming I think the OP's backtrace is sufficient to answer your question. Not well implemented is besides the point here: non-standard libraries should define their own exception type(s) if they assume they're the only one to raise them. The example is to show that.

**Comment by frostming** [comment]
`json`'s `default=` argument also expects a `TypeError` to skip the encoder, we just follow the same convention.

**Comment by sanmai-NL** [comment]
It could be a suboptimal design, more of Python's standard library suffers from that.

You could enforce using a _subclass_ of `TypeError` for the custom encoder to improve the design.

To illustrate your example, can you show how the custom encoder gets invoked? I don't see that in the example which makes it harder to comment on the appropriateness of the exception message.

**Comment by frostming** [comment]
Okay, I am convinced.
